### ISSUE TITLE
pixi-pack 0.2.2 exits the terminal on Command Prompt

### ISSUE THREAD

**Issue by traversaro** [Quantco/pixi-pack#72] opened 2024-11-21 19:02 UTC
Hello, and thanks a lot for all the work on pixi-pack! 

I used pixi-pack on Windows, and while it works fine on PowerShell, when I tried to run it in the command prompt, and I experienced some problems:

* Running `pixi-pack`, results in the following restart of the prompt:

~~~
C:\Users\straversaro>pixi-pack
A command line tool to pack and unpack conda environments for easy sharing

Usage: pixi-pack.exe [OPTIONS] <COMMAND>

Commands:
  pack    Pack a pixi environment
  unpack  Unpack a pixi environment
  help    Print this message or the help of the given subcommand(s)

Options:
  -v, --verbose...  Increase logging verbosity
  -q, --quiet...    Decrease logging verbosity
  -h, --help        Print help
  -V, --version     Print version

[process exited with code 2 (0x00000002)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
Microsoft Windows [Version 10.0.22631.4317]
(c) Microsoft Corporation. All rights reserved.

C:\Users\straversaro>
~~~

* Running `pixi-pack pack` works, but the relative terminal is closed as soon as the archive is created.

**Comment by delsner** [comment] 2024-11-25 09:59
I can't reproduce the bug on Microsoft Windows Server 2019 Standard. Can you please run `SYSTEMINFO` in `cmd.exe` and post the output here?

**Comment by pavelzw** [comment] 2024-12-10 13:54
closing for now. feel free to reopen/ping us if this still occurs/there is any more input

**Closed by pavelzw** 2024-12-10 13:54 UTC
Labels: bug
